#!/bin/bash

#shashi install
#update packages
echo "Need to switch the user to root else some of the dependencies will not be installed properly, can we go ahead"
apt-get update

#install hostapd, dnsmasq
apt-get install -y hostapd
apt-get install -y dnsmasq

#remove hostapd mask
systemctl unmask hostapd

#stop both services
systemctl disable hostapd
systemctl disable dnsmasq

mkdir -p $HOME/temp

wifipass () {
echo;echo;echo
echo "This password will be used to connect to the pi"
echo "when the pi is in hotspot mode"
#credit next line to Ray, N3HYM
echo "Password should be between 8-63 characters"
read -p "Enter password to use with new hotspot " wifipasswd
echo;echo
echo "You entered $wifipasswd"
read -p "Is this correct? y/n " wifians
if [ $wifians == "y" ]
then
echo
else
wifipass
fi
}

wifipass

cd $HOME/temp

wget https://raw.githubusercontent.com/lordcast/rpi_hotspot_mavlink/master/hostapd.txt

#set new hotspot passwd
sed -i "s/wpa_passphrase=1234567890/wpa_passphrase=$wifipasswd/" $HOME/temp/hostapd.txt
#set country to IN
sed -i 's/country_code=GB/country_code=US/' $HOME/temp/hostapd.txt

#move hostapd to correct location
mv $HOME/temp/hostapd.txt /etc/hostapd/hostapd.conf

sed -i s'/#DAEMON_CONF=""/DAEMON_CONF="\/etc\/hostapd\/hostapd.conf"/' /etc/default/hostapd
sed -i s'/DAEMON_OPTS=""/#DAEMON_OPTS=""/' /etc/default/hostapd

#add needed info to dnsmasq.conf
echo "#AutoHotspot config" >> /etc/dnsmasq.conf
echo "interface=wlan0" >> /etc/dnsmasq.conf
echo "bind-dynamic" >> /etc/dnsmasq.conf
echo "server=8.8.8.8" >> /etc/dnsmasq.conf
echo "domain-needed" >> /etc/dnsmasq.conf
echo "bogus-priv" >> /etc/dnsmasq.conf
echo "dhcp-range=10.10.10.150,10.10.10.200,255.255.255.0,12h" >> /etc/dnsmasq.conf
echo "#Set up redirect for email.com" >> /etc/dnsmasq.conf
echo "dhcp-option=3,10.10.10.10" >> /etc/dnsmasq.conf
echo "address=/email.com/10.10.10.10" >> /etc/dnsmasq.conf

mv /etc/network/interfaces /etc/network/interfaces.org

echo "source-directory /etc/network/interfaces.d" >> /etc/network/interfaces


echo "nohook wpa_supplicant" >> /etc/dhcpcd.conf

#setup ip forward
sed 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf

cd $HOME/temp

wget https://raw.githubusercontent.com/lordcast/rpi_hotspot_mavlink/master/autohotspot-service.txt

#create autohotspot service file
mv autohotspot-service.txt /etc/systemd/system/autohotspot.service

#start autohotspot service
systemctl enable autohotspot.service

#check if iw installed. install if not

iwcheck=$(dpkg --get-selections | grep -w "iw")
if [ -z "iw" ]
then
apt-get install iw
fi

#install autohotspot script
cd $HOME/temp
wget https://raw.githubusercontent.com/lordcast/rpi_hotspot_mavlink/master/autohotspotN.txt
#mod ip address for our custom setup
sed -i 's/192.168.50.5/10.10.10.10/' autohotspotN.txt
mv autohotspotN.txt /usr/bin/autohotspotN
chmod +x /usr/bin/autohotspotN

#shackwifi function
shackwifi1 () {
#get ham's wifi credentials
echo "What wifi SSID would you like to connect to?"
echo "This is the one already in your shack"
read shackwifi
echo "What is the password for this wifi?"
read shackpass

echo;echo;
echo "Your shack's current wifi is"
echo "wifi $shackwifi"
echo "passwd $shackpass"
echo "Is this correct? y/n"
read shackans
if [ $shackans == "y" ]
then
echo
else
shackwifi1
fi
}

#run shackwifi function
shackwifi1

#add shack wifi to wpa_supplicant.conf
echo "network={" >> /etc/wpa_supplicant/wpa_supplicant.conf
echo "ssid=\"$shackwifi\"" >> /etc/wpa_supplicant/wpa_supplicant.conf
echo "psk=\"$shackpass\"" >> /etc/wpa_supplicant/wpa_supplicant.conf
echo "key_mgmt=WPA-PSK" >> /etc/wpa_supplicant/wpa_supplicant.conf
echo "}" >> /etc/wpa_supplicant/wpa_supplicant.conf

echo;echo;echo
echo "A reboot is required to complete the setup"

echo "Now installing mavlink-router and there dependencies"
sudo apt-get install autoconf automake pkg-config libgtk-3-dev libtool git

echo "Creating mavlink-router folder and cloning repo"
sudo git clone https://github.com/intel/mavlink-router.git
sudo mkdir mavlink-router
sudo cd mavlink-router
git submodule update --init --recursive

./autogen.sh && ./configure CFLAGS='-g -O2' --sysconfdir=/etc --localstatedir=/var --libdir=/usr/lib64 --prefix=/usr
sudo make install

echo "Making service of mavlink-router" 

wget https://raw.githubusercontent.com/lordcast/rpi_hotspot_mavlink/master/main.conf
wget https://raw.githubusercontent.com/lordcast/rpi_hotspot_mavlink/master/mavlink-router.service

sudo mkdir /etc/mavlink-router
sudo mv main.conf /etc/mavlink-router/main.conf
sudo mv mavlink-router.service /etc/systemd/system/mavlink-router.service

echo "Enabling the service mavlink-router"
sudo systemctl enable mavlink-router.service

echo "Starting the service of mavlink-router"
sudo systemctl start mavlink-router.service

echo "Router will not work until reboot, reboot now? y/n"
read rebootnow
if [rebootnow == "y"]
then
sudo reboot
else
echo "Reboot required until the changes will not take be implemented"
exit 0